database/migrations/2023_03_14_101121_change_mobile_no_in_users_table.php
Remove the unique field of mobile no in users table.
=> Remove the unique field of mobile no in users table.

app/Http/Controllers/BannerController.php, resources/views/banner/banner.blade.php, resources/views/banner/bannercreate.blade.php, resources/views/layouts/footer.blade.php, resources/views/layouts/layout.blade.php, routes/web.php
create banner controller and footer section.
=> create banner controller and footer section.

app/Http/Controllers/CategoryController.php, app/Http/Controllers/MainCategoryController.php, app/Http/Controllers/MasterCategoryController.php, app/Http/Controllers/SubCategoryController.php, app/Models/CategorySubCategory.php, app/Models/MainCategoryCategory.php, app/Models/SubCategory.php, database/migrations/2023_03_20_063937_create_maincategorycategory-table.php, database/migrations/2023_03_20_092443_create_categorysubcategory-table.php, database/migrations/2023_03_20_092702_create_subcategory-table.php, resources/views/category/category.blade.php, resources/views/category/categoryadd.blade.php, resources/views/category/categoryedit.blade.php, resources/views/category/categoryshow.blade.php, resources/views/maincategory/maincategoryedit.blade.php, resources/views/mastercategory/mastercategoryedit.blade.php, resources/views/subcategory/subcategory.blade.php, resources/views/subcategory/subcategoryadd.blade.php, resources/views/subcategory/subcategoryedit.blade.php, resources/views/subcategory/subcategoryshow.blade.php, routes/web.php
Main category,category and sub category crud
=> Main category,category and sub category crud

app/Http/Controllers/Api/AddressController.php, app/Http/Controllers/Auth/GuestUserController.php, app/Http/Controllers/Auth/UserAuthController.php
=> Fetched address user id wise.

app/Http/Controllers/Api/CategoryController.php, routes/api.php
=> Master-Main category api

app/Http/Controllers/ProductController.php, app/Models/ProductCategory.php, app/Models/ProductLocation.php, app/Models/ProductMainCategory.php, app/Models/ProductMasterCategory.php, app/Models/ProductSubCategory.php, app/Models/ProductsImage.php, database/migrations/2023_03_21_060411_create_products_table.php, database/migrations/2023_03_21_063731_create_productsmastercategory_table.php, database/migrations/2023_03_21_064342_create_productscategory_table.php, database/migrations/2023_03_21_064428_create_productssubcategory_table.php, database/migrations/2023_03_21_074027_create_productscategoryimage_table.php, database/migrations/2023_03_21_092010_create_productsmaincategory_table.php, database/migrations/2023_03_24_063647_create_productslocation_table.php, resources/views/layouts/layout.blade.php, resources/views/product/product.blade.php, resources/views/product/productadd.blade.php, resources/views/product/productedit.blade.php, resources/views/product/productshow.blade.php, routes/web.php
=> Added file of Product Module.

app/Http/Controllers/Api/HomeController.php, app/Http/Controllers/OfferProductController.php, app/Models/ExploreProductOffer.php, app/Models/ExploreProductOfferProduct.php, database/migrations/2023_03_28_064447_create_exploreproductofferproduct_table.php, database/migrations/2023_03_28_070146_create_exploreproductoffer_table.php, public/site/css/bala.DualSelectList.css, public/site/js/bala.DualSelectList.jquery.js, resources/views/layouts/footer.blade.php, resources/views/layouts/layout.blade.php, resources/views/offerproduct/offerproduct.blade.php, resources/views/offerproduct/offerproductadd.blade.php, routes/web.php
Offer Product module and get offer product data API
=> Offer Product module and get offer product data API

app/Http/Controllers/Api/HomeController.php, database/migrations/2023_03_28_111532_change_quantity_in_products_table.php, database/migrations/2023_03_28_114001_change_product_details_in_products_table.php, resources/views/product/productadd.blade.php, resources/views/product/productedit.blade.php
change quantity field and added product quantity
=> change quantity field and added product quantity

app/Http/Controllers/Api/ProductMasterController.php
=> Added base url for image

app/Http/Controllers/OfferProductController.php, public/site/js/bala.DualSelectList.jquery.js, resources/views/offerproduct/offerproduct.blade.php, resources/views/offerproduct/offerproductedit.blade.php, routes/web.php
Fetched the product data edit the offer product data store in db.
=> Fetched the product data edit the offer product data store in db.

public/site/js/bala.DualSelectList.jquery.js
Product edit page displaying old selected products
=> Product edit page displaying old selected products

app/Http/Controllers/Api/CartController.php, app/Models/Cart.php, app/Models/CartProduct.php, database/migrations/2023_03_29_074803_create_cart_table.php, database/migrations/2023_03_29_075124_create_cart_product_table.php, database/migrations/2023_03_30_050100_add_product_quantity_to_cart_product_table.php, routes/api.php
(Cart API)cart data store in cart and cart product table.
=> (Cart API)cart data store in cart and cart product table.

app/Http/Controllers/Api/CartController.php, routes/api.php
update cart product and delete cart product
=> update cart product and delete cart product

app/Http/Controllers/Api/ProductMasterController.php
Mastter,main and category wise product fetched.
=> Mastter,main and category wise product fetched.

app/Http/Controllers/Api/ProductMasterController.php, routes/api.php
=> change of the required field.

app/Http/Controllers/Api/CartController.php
show product details by cart_id
=> show product details by cart_id

app/Http/Controllers/ExploreController.php, app/Models/Explore.php, app/Models/ExploreExploreCategory.php, database/migrations/2023_03_28_074057_create_exploreexplorecategory_table.php, database/migrations/2023_03_28_074119_create_explore_table.php, resources/views/explore/explore.blade.php, resources/views/explore/explorecreate.blade.php, resources/views/explore/exploreedit.blade.php, resources/views/layouts/layout.blade.php, routes/web.php
=> Explore Module

resources/views/explore/exploreedit.blade.php
=> added base url for ajax call.

app/Http/Controllers/BannerCategoryController.php, app/Http/Controllers/ExploreController.php, app/Models/BannerCategory.php, database/migrations/2023_04_01_094528_create_bannercategory_table.php, resources/views/bannercategory/bannercategory.blade.php, resources/views/bannercategory/bannercategorycreate.blade.php, resources/views/layouts/layout.blade.php, routes/web.php
=> Banner Category Module

app/Http/Controllers/Api/CartController.php
When the cart is empty then displaying message.
=> When the cart is empty then displaying message.

app/Http/Controllers/Api/AddressController.php, routes/api.php
Address delete and Address update API
=> Address delete and Address update API

app/Http/Controllers/Api/CheckOutController.php, routes/api.php
=> Checkout API

app/Http/Controllers/Api/CartController.php
=> Get Product image in cart api

routes/web.php
change the route path in ajax calling
=> change the route path in ajax calling

app/Http/Controllers/Api/ProductCategoryController.php
Added Sale and Sale Price In Product Category API
=> Added Sale and Sale Price In Product Category API

app/Http/Controllers/Api/SearchController.php, routes/api.php
=> added search api

app/Http/Controllers/Api/SearchController.php
=> added search field required

public/site/js/bala.DualSelectList.jquery.js
Fix the issue of product search in offer product module
=> Fix the issue of product search in offer product module

resources/views/bannercategory/bannercategory.blade.php, resources/views/layouts/layout.blade.php
=> Changes of the layout

app/Http/Controllers/Api/UserProfileController.php, routes/api.php
=> edit user profile api

resources/views/product/product.blade.php
Product list page product detail is bigger then displaying Three dots
=> Product list page product detail is bigger then displaying Three dots

app/Http/Controllers/Api/HomeController.php
Added explore Category API on Home Page
=> Added explore Category API on Home Page

app/Http/Controllers/BannerCategoryController.php, resources/views/bannercategory/bannercategoryadd.blade.php
Feature bannercategory module copy
=> Feature bannercategory module copy

app/Http/Controllers/Api/HomeController.php
Changes in Explore category API name
=> Changes in Explore category API name

app/Http/Controllers/Api/ProductController.php
Added multiple image on product details.
=> Added multiple image on product details.

app/Http/Controllers/Api/HomeController.php
added the banner category in home page api
=> added the banner category in home page api

app/Http/Controllers/Api/HomeController.php
Change the variable to Banner Data fetch
=> Change the variable to Banner Data fetch

app/Http/Controllers/Api/CartController.php
display messagecode and total order in response
=> display messagecode and total order in response

app/Http/Controllers/Api/HomeController.php
display Banner category vis Product On homepage API
=> display Banner category vis Product On homepage API

app/Http/Controllers/Api/HomeController.php
change the key name of banner category product
=> change the key name of banner category product

app/Http/Controllers/Api/ProductCategoryController.php, app/Http/Controllers/MainCategoryController.php, app/Models/MainCategory.php, database/migrations/2023_04_11_065607_add_main_category_banner_image_to_maincategory_table.php, resources/views/maincategory/maincategoryadd.blade.php, resources/views/maincategory/maincategoryedit.blade.php, resources/views/maincategory/maincategoryshow.blade.php
added main category banner image field crud and api
=> added main category banner image field crud and api

resources/views/category/categoryshow.blade.php
=> Change the field name

app/Http/Controllers/Api/BannerCategoryProductController.php, app/Http/Controllers/BannerController.php, app/Models/Banner.php, database/migrations/2023_04_10_103606_add_mastercategory_id_maincategory_id_category_id_and_subcategory_id_to_banners.php, database/migrations/2023_04_12_051553_add_status_to_banner.php, resources/views/banner/banner.blade.php, resources/views/banner/banneradd.blade.php, resources/views/banner/banneredit.blade.php, resources/views/banner/bannershow.blade.php, routes/api.php
added banner categories in banner module and create api for the same.
=> added banner categories in banner module and create api for the same.

app/Http/Controllers/Api/CartController.php
=> make changes in cart api

app/Http/Controllers/Api/CartController.php
added cart_id in user cart api
=> added cart_id in user cart api

resources/views/product/product.blade.php
added displayed the status like available and unavailable in product blade.
=> added displayed the status like available and unavailable in product 

app/Http/Controllers/Api/CartController.php
added product count and displayed latest 10 product in cart api
=> added product count and displayed latest 10 product in cart api

app/Http/Controllers/BannerController.php, resources/views/banner/banneradd.blade.php, resources/views/banner/banneredit.blade.php, resources/views/banner/bannershow.blade.php, routes/web.php
added the banner(categories)module.
=> added the banner(categories)module.

app/Http/Controllers/Api/ProductController.php
added status in product details api
=> added status in product details api

app/Http/Controllers/CategoryController.php, app/Http/Controllers/ExploreController.php, app/Http/Controllers/MainCategoryController.php, app/Http/Controllers/SubCategoryController.php, resources/views/offerproduct/offerproduct.blade.php
displaying the category which have status = 1
=> displaying the category which have status = 1

app/Http/Controllers/OfferProductController.php
Remove the data from multiple products in offer product
=> Remove the data from multiple products in offer product

app/Http/Controllers/Api/LogoutController.php, routes/api.php
=> logout api

app/Http/Controllers/Api/LogoutController.php
added massege in json response in logout api
=> added massege in json response in logout api

app/Http/Controllers/BannerController.php
Change the condition for the banner module.
=> Change the condition for the banner module.

app/Http/Controllers/Api/CategoryController.php
displaying those categories which have status 1 in mastarmain category api.
=> Feature allstatusadd module api

app/Http/Controllers/ProductController.php
Description field required minimum 15 characters.
=> Description field required minimum 15 characters.

app/Http/Controllers/BannerController.php
Banner module status field required.
=> Banner module status field required.

app/Http/Controllers/ProductController.php, app/Models/Product.php, database/migrations/2023_04_17_041617_add_packet_to_products_table.php, resources/views/product/productadd.blade.php, resources/views/product/productedit.blade.php, resources/views/product/productshow.blade.php
added packet field in product module
=> added packet field in product module

resources/views/product/productadd.blade.php, resources/views/product/productedit.blade.php
changed the structure of product add and edit page.
=> changed the structure of product add and edit page.

app/Http/Controllers/Api/ProductController.php
added random product functionality in product details api
=> added random product functionality in product details api

app/Http/Controllers/Api/CartController.php
Added random data functionality in usercart api
=> Added random data functionality in usercart api

app/Http/Controllers/Api/ProductController.php
make changes in product details api
=> make changes in product details api

database/migrations/2023_04_14_100357_drop_status_from_cart_table.php, database/migrations/2023_04_14_100930_add_status_to_cart_table.php
added two migration file in add to cart api
=> added two migration file in add to cart api

app/Http/Controllers/ProductController.php, resources/views/product/product.blade.php, resources/views/product/productadd.blade.php, resources/views/product/productedit.blade.php, resources/views/product/productshow.blade.php
sale and sale price filed dependency.
=> sale and sale price filed dependency.

app/Http/Controllers/Api/CartController.php
added message code and message in usercart api
=> added message code and message in usercart api

app/Http/Controllers/Api/CategoryController.php
added base url in mastercategory api
=> added base url in mastercategory api

app/Http/Controllers/Api/UserProfileController.php, routes/api.php
=> edit mobile number api.

app/Http/Controllers/Api/SearchController.php, routes/api.php
=> change the function name.

app/Http/Controllers/Api/ByItAgainController.php, routes/api.php
=> By It Again API

app/Http/Controllers/Api/CartController.php
=> change key name

app/Http/Controllers/Api/CartController.php
added cart_id and message code.
=> added cart_id and message code.

app/Http/Controllers/Api/CartController.php
added massage,messagecode and cart_id in usercart api.
=> added massage,messagecode and cart_id in usercart api.

app/Http/Controllers/Api/HomeController.php
Changes in image, status in home page API
=> Changes in image, status in home page API

app/Http/Controllers/Api/HomeController.php
=> change in home page api

app/Models/ProductAllCategory.php, database/migrations/2023_04_20_062624_create_productallcategory_table.php
added productallcatgeory model and migration table
=> added productallcatgeory model and migration table

app/Http/Controllers/ProductController.php, app/Models/ProductAllCategory.php
Change table name in Product Controller and product all category model
=> Change table name in Product Controller and product all category model

resources/views/product/product.blade.php, resources/views/product/productadd.blade.php, resources/views/product/productedit.blade.php, resources/views/product/productshow.blade.php
Made changes in product module
=> Made changes in product module

app/Http/Controllers/Api/HomeController.php
Made Changes in home page API(image)
=> Made Changes in home page API(image)

app/Http/Controllers/Api/ProductCategoryController.php, routes/api.php
Change in Product category API
=> Change in Product category API

app/Http/Controllers/Api/BuyItAgainController.php, app/Http/Controllers/Api/CartController.php, app/Http/Controllers/Api/ExploreController.php, app/Http/Controllers/Api/ProductController.php, app/Http/Controllers/Api/SearchController.php
=> Change in image slash.

app/Http/Controllers/Api/CategoryController.php, app/Http/Controllers/Api/SearchController.php
change in search and category controller
=> change in search and category controller

app/Http/Controllers/Api/ProductCategoryController.php
Change key in product categories API
=> Change key in product categories API

app/Http/Controllers/CategoryController.php, app/Http/Controllers/MainCategoryController.php, app/Http/Controllers/MasterCategoryController.php, app/Http/Controllers/SubCategoryController.php
Changed Delete Functionality Hard Delete to Soft Delete(isActive Status Update) and Dependency Categories are also Deleted with his Data And Product
=> Changed Delete Functionality Hard Delete to Soft Delete

app/Http/Controllers/CategoryController.php, app/Http/Controllers/MainCategoryController.php, app/Http/Controllers/MasterCategoryController.php, app/Http/Controllers/SubCategoryController.php, resources/views/subcategory/subcategory.blade.php
changes in single new data insert
=> changes in single new data insert

app/Http/Controllers/BannerCategoryController.php, app/Http/Controllers/BannerController.php, app/Http/Controllers/CategoryController.php, app/Http/Controllers/ExploreController.php, app/Http/Controllers/MainCategoryController.php, app/Http/Controllers/OfferProductController.php, app/Http/Controllers/ProductController.php, app/Http/Controllers/SubCategoryController.php
isActive add on in all Controller
=> isActive add on in all Controller

app/Http/Controllers/Api/BannerCategoryProductController.php, app/Http/Controllers/Api/CategoryController.php, app/Http/Controllers/Api/ExploreController.php, app/Http/Controllers/Api/HomeController.php, app/Http/Controllers/Api/ProductCategoryController.php, app/Http/Controllers/Api/ProductController.php, routes/api.php
Added isActive filed in all API
=> Added isActive filed in all API

app/Http/Controllers/Api/CartController.php
=> fix the issue in cart API

app/Http/Controllers/Api/ProductCategoryController.php, routes/api.php
Change name of without limit API
=> Change name of without limit API

app/Http/Controllers/Api/CartController.php, app/Http/Controllers/Api/CheckOutController.php
Changes of checkout API and show cart API.
=> Changes of checkout API and show cart API.

app/Http/Controllers/Api/BannerCategoryProductController.php, routes/api.php
all banner category product api.
=> all banner category product api.

app/Http/Controllers/Api/BannerCategoryProductController.php
Change image slash in bannercategoryproduct API
=> Change image slash in bannercategoryproduct API

app/Http/Controllers/Api/HomeController.php
remove key in banner category product in home page api.
=> remove key in banner category product in home page api.

app/Http/Controllers/Api/CategoryController.php
Added Master category id in mastermain category API.
=> Added Master category id in mastermain category API.

app/Http/Controllers/Api/CategoryController.php
added product based main categry in category api.
=> added product based main categry in category api.

app/Http/Controllers/Api/HomeController.php, app/Http/Controllers/BannerCategoryController.php
display only those category who have product
=> display only those category who have product

database/migrations/2023_06_02_111235_add_is_active_to_products_all_category_table.php
added new column 'isActive' in products_all_category
=> added new column 'isActive' in products_all_category

app/Http/Controllers/Api/ProductCategoryController.php, app/Http/Controllers/ProductController.php
product tag in those category which have zero product
=> product tag in those category which have zero product

app/Http/Controllers/Api/HomeController.php
=> hasProducts will remained

app/Http/Controllers/Api/HomeController.php
Explore category conditional error
=> Explore category conditional error

app/Http/Controllers/Api/CartController.php
=> changes in cart controller

app/Http/Controllers/ExploreController.php
Show only explore with no duplicate data in Store function
=> Show only explore with no duplicate data in Store function

app/Http/Controllers/Api/HomeController.php
=> Added Other Category Logic

app/Http/Controllers/Api/MyOrderController.php, app/Models/Order.php, database/migrations/2023_05_16_051751_create_order_table.php, database/migrations/2023_05_30_063516_add_user_id_to_order_table.php, database/migrations/2023_05_30_063739_add_status_to_order_table.php, routes/api.php
=> Added Order API

app/Http/Controllers/Api/UserProfileController.php, routes/api.php
fetch user details after edit functionality performed
=> fetch user details after edit functionality performed

app/Models/User.php
added hidden field in user module
=> added hidden field in user module

app/Http/Controllers/Api/UserProfileController.php
Changed in edit mobile number api in UserProfile Controller
=> Changed in edit mobile number api in UserProfile Controller

app/Http/Controllers/Api/ExploreController.php, app/Http/Controllers/Api/HomeController.php, routes/api.php
Created new function exploreAllProductsOffer without limit and added limit of product in Home API
=> Created new function exploreAllProductsOfferwithout limit
